apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v1s2h2nvy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v1s2h2nvy-go 
  name: v1s2h2nvy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v1s2h2nvy-go 
